### ISSUE TITLE
[Bug]: Broken draggable cards functionality

### ISSUE THREAD

**Issue by Us3r-gitHub** [tillywork/tillywork#105]
# Scope

Occurs when groupBy is either Assignee or Due Date

https://github.com/tillywork/tillywork/assets/58467104/909cc6b1-4cee-4155-a5ad-9fefe6573360

https://github.com/tillywork/tillywork/assets/58467104/dca0ab14-101e-4aa6-924d-70b4539c5672

**Comment by MoShizzle** [comment]
Fixed by #200
