### ISSUE TITLE
Card Title can Have Multiple Lines

### ISSUE THREAD

**Issue by codonade** [tillywork/tillywork#123]
![Tillywork Multiple Card Title Lines](https://github.com/tillywork/tillywork/assets/141618497/d6c95d19-8fda-428a-94a9-af60d23961df)

I've noticed that you cannot go to a new line by pressing `Enter`, you can only go with the down arrow key. Also, the issue occurs in the card create dialog, not just the card view.

**Comment by MoShizzle** [comment]
This should already be fixed in https://github.com/tillywork/tillywork/commit/60dcc2bf952ec73ed271d6c14f4473e4e3ea5b10, is it still an issue?

**Comment by codonade** [comment]
Ah... this wasn't committed yet when I merged... It's resolved.
