### ISSUE TITLE
Display assignee name

### ISSUE THREAD

**Issue by Us3r-gitHub** [tillywork/tillywork#132]
Currently, the username is not displayed. To clarify the assigned user, we can show either the username or the full name.

![image](https://github.com/tillywork/tillywork/assets/58467104/41d046c8-a5aa-48e1-9735-02ff9a3b9544)

**Comment by codonade** [comment]
I feel like showing the full name in the assignees field itself would take a lot of space. One suggestion I have is to have some sort of tooltip that shows the full name when you hover over the user's avatar.

**Comment by MoShizzle** [comment]
We won't show the name here to conserve space. Closing.

**Comment by Us3r-gitHub** [comment]
I think there's a possibility of having similar Avatar icons.

How can we distinguish between them?
For example: 
Ahmad Maulana and Abdul Munib

**Comment by Us3r-gitHub** [comment]
What if we add new column `nickname`?
Or should we just use `username`?

I think it should be short to avoid overflowing space.
