### ISSUE TITLE
Cannot Switch Between Workspaces

### ISSUE THREAD

**Issue by codonade** [tillywork/tillywork#136]
The created workspaces stopped appearing in the navigation drawer, hence you cannot really switch between them:

![Tillywork Workspaces Bug](https://github.com/tillywork/tillywork/assets/141618497/e924b805-263f-42c1-8ce9-e1837842450a)

I've noticed an error is being thrown from the `WorkspacesController.findAll` function:

```
[Nest] 3007006  - 07/09/2024, 12:19:56 PM   ERROR [HTTP] req-67 - GET /v1/workspaces?type=project_management - 200 - 0.18ms
Error: Cannot read properties of undefined (reading 'id')

[Nest] 3007006  - 07/09/2024, 12:19:56 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'id')
TypeError: Cannot read properties of undefined (reading 'id')
    at WorkspacesController.findAll (/home/codonade/forks/tillywork/dist/packages/backend/main.js:6039:34)
    at /home/codonade/forks/tillywork/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MoShizzle** [comment]
Log out and log in, it should work. This is due to changes in JWT signing for logged in users.

**Comment by codonade** [comment]
> Log out and log in,

I'll try that.

**Comment by codonade** [comment]
Working like a charm, thanks.
