### ISSUE TITLE
Migrate settings dialog from a dialog using v-tabs to a page with it's own navigation drawer

### ISSUE THREAD

**Issue by MoShizzle** [tillywork/tillywork#158]
The current settings dialog is usable, but ugly. It is hard to space things correctly using v-tabs.

The settings dialog should be it's own route page, and similar to how you navigate different lists you should select the tab needed in the settings page nav drawer.

This makes it more expandable and easier to style.

**Comment by MoShizzle** [comment]
@codonade would you like to be assigned this?

**Comment by codonade** [comment]
> @codonade would you like to be assigned this?

I'll be happy to resolve this.

> and similar to how you navigate different lists you should select the tab needed in the settings page nav drawer.

Can you clarify this more? I didn't quite get what you want...

**Comment by Us3r-gitHub** [comment]
I think to be like settings dialog like list/card

Convert it be page instead of dialog component

**Comment by codonade** [comment]
Ah okay. Thank you for the clarification.
