### ISSUE TITLE
Strange database migration errors on self-deploy / watch build

### ISSUE THREAD

**Issue by mtyszczak** [tillywork/tillywork#212]
## Bug description

When following your [deployment documentation](https://docs.tilly.work/getting-started/using-tillywork/) I stumbled upon some strange database-related errors, which prevented me from running the backend. It has something to do with the migration files.

## Relevant log output

```
Migration "AddFieldIdAndFilterToListGroupTable1723106937425" failed, error: invalid input value for enum view_groupby_enum: "assignee"
[Nest] 626557  - 10/03/2024, 1:32:44 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (4)...
QueryFailedError: invalid input value for enum view_groupby_enum: "assignee"
```

```
Migration "MigrateCardUsersToDataColumn1725792730053" failed, error: invalid input value for enum list_group_type_enum: "assignee"
[Nest] 628726  - 10/03/2024, 1:34:41 AM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (8)...
QueryFailedError: invalid input value for enum list_group_type_enum: "assignee"
```

## Steps to reproduce

1. Clone your repository
2. Configure database (fresh user & database) using `.env` file (Also test the connection)
3. Run `npm install`
4. Run `npm run dev`

Or:

1. Configure database (fresh user & database)
2. Pull & run docker image with proper environment variables setup

## "Workaround"

For users who do not want to wait for the fixup

After running the docker image / `npm run dev`:
```
ALTER TABLE IF EXISTS public.view
    ALTER COLUMN "groupBy" TYPE varchar (20);
ALTER TYPE public.list_group_type_enum
    ADD VALUE 'assignee' AFTER 'field';
```
This query changes the `groupBy` column type so it ignores invalid enum values and modifies the `list_group_type_enum` enum by adding missing value - `assignee`

## OS / Versions

- npm version: `10.8.2`
- Node.js version: `22.8.0`
- docker version: `24.0.7`
- Os: `Linux x86_64, Ubuntu 24.04 LTS`
- PostgreSQL: `PostgreSQL 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0, 64-bit`

**Comment by MoShizzle** [comment]
Fixed by #218
