### ISSUE TITLE
Stages don't reorder and some stages can't be edited

### ISSUE THREAD

**Issue by danielemezzetti** [tillywork/tillywork#232]
On tilly.work, editing stages order do not reflects in changing the order of display on table or board view.
Also, some stages can't be edited e.g. if I try to change "Done" to "Fatto" a message appears stating "Something went wrong"

**Comment by MoShizzle** [comment]
Regarding changing the order, can you provide steps to reproduce the issue?

**Comment by danielemezzetti** [comment]
These are the stages
![image](https://github.com/user-attachments/assets/db72c498-bb90-4172-bbf2-aef75ab8148e)
I would like to change the order, so I drag them in the desired position
![image](https://github.com/user-attachments/assets/423bc275-18b1-4fbc-8daf-39ca6cacf51e)
There is no "OK" button, so I simply close the dialog
The view underneath, grouped by stages, does not change as expected
![image](https://github.com/user-attachments/assets/4ccc78ef-a2fc-457f-8a0f-76a5b2517107)
and if I reopen the stages dialog the stages themselves have not changed order
![image](https://github.com/user-attachments/assets/d8da94be-cec6-43d0-8de5-f04c63f3e436)

Also, if I try to change the last stage label e.g. "Fatto", instead of "Done" the program complains that "somethin went wrong" and does not accept the change.
![image](https://github.com/user-attachments/assets/6c2b0ef6-e477-4d7b-9c63-f35cd97e56bb)

I've seen that sometimes, editing the stage labels changes the order of them and this actually reflects in the view underneath, but this effect does not seem to follow an understandable pattern (sometimes it happens, other times not)
