### ISSUE TITLE
Command Palette Card Creation

### ISSUE THREAD

**Issue by MoShizzle** [tillywork/tillywork#99]
In the command palette, currently we display a section called 'Card' with one command: 'Create Card'.

To make this more usable along the custom card types/workspace types system, the behavior should be as follows:

- For each card type in a workspace, we display a section for that type, e.g 'Task' instead of 'Card'
- Under each type, you can create a card for that entity type (similar to current behavior, but the card type changes for each command instead of following the list card type)

**Comment by codonade** [comment]
> Under each type, you can create a card for that entity type (similar to current behavior, but the card type changes for each command instead of following the list card type)

You mean to let the user create any card type in a given list, not just the default one assigned to that list?

**Comment by MoShizzle** [comment]
> > Under each type, you can create a card for that entity type (similar to current behavior, but the card type changes for each command instead of following the list card type)
> 
> You mean to let the user create any card type in a given list, not just the default one assigned to that list?

Yes, but each entity has it's own section
